### ISSUE TITLE
Getting error when running ssh agent

### ISSUE THREAD

**Issue by martintreurnicht** [LedgerHQ/blue-app-ssh-agent#2]
Using Nano S with firmware 1.2 on OSX 10.12, get the following error when running `python getPublicKey.py`:

```bash
=> 8002000115058000002c80082b34800000000000000000000000
<= 6e00
Traceback (most recent call last):
  File "getPublicKey.py", line 63, in <module>
    result = dongle.exchange(bytes(apdu))
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/comm.py", line 128, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00
```

Device is plugged in and unlocked using pin

**Comment by btchip** [comment]
Did you select the GPG/SSH app before ?

**Comment by romanz** [comment]
Seems like it was indeed the issue here: https://github.com/romanz/trezor-agent/issues/59#issuecomment-255051192
After installing and selecting the SSH/PGP app, SSH and GPG with (nistp256 keys) seem to work correctly.

**Comment by btchip** [comment]
ok, should just make it more clear in the documentation (that I didn't contribute to yet, sorry). Can close this one.

**Comment by martintreurnicht** [comment]
@btchip Yes this was related to not running the app, stupid mistake from my side. For some reason i thought it was just built into the device, no app needed. This is a super feature, i'll be using this full time
