### ISSUE TITLE
Syntax error when running getPublicKey

### ISSUE THREAD

**Issue by Christewart** [LedgerHQ/blue-app-ssh-agent#9]
Just tried to run this script and got an error: 

```
$ python3 getPublicKey.py
  File "getPublicKey.py", line 69
    if ((keyX[31] & 1)<>0):
                       ^
SyntaxError: invalid syntax

```

**Comment by btchip** [comment]
Yes, it only works with Python 2 - I'd also suggest using https://github.com/romanz/trezor-agent as a client as it supports more use cases.
